DECLARE  @m int
set @m = DATEDIFF(mi,SYSUTCDATETIME(), SYSDATETIME())

SELECT 
	CASE [BATCHHISTORY].[STATUS]
		WHEN 0 THEN N'Withhold'
		WHEN 1 THEN N'Waiting'
		WHEN 2 THEN N'Executing'
		WHEN 3 THEN N'Error'
		WHEN 4 THEN N'Ended'
		WHEN 5 THEN N'Ready'
		WHEN 6 THEN N'Didn''t run'
		WHEN 7 THEN N'Cancelling'
		WHEN 8 THEN N'Cancelled'
		WHEN 9 THEN N'Scheduled'
		ELSE CONVERT(nvarchar, [BATCHHISTORY].[STATUS])
	END as [STATUS]
      ,[BATCHJOBHISTORY].[CAPTION] as [BatchCaption]
      ,[BATCHHISTORY].[CAPTION]    as [TaskCaption]
      ,[BATCHHISTORY].[BATCHJOBID]
	  ,[BATCHHISTORY].SERVERID
	  ,(SELECT TOP 1 [Name] FROM [CLASSIDTABLE] where ID = [BATCHHISTORY].CLASSNUMBER ) as ClassName
	  ,[BATCHHISTORY].CLASSNUMBER
	  ,DATEADD(minute, @m, ORIGSTARTDATETIME) as [ORIGSTARTDATETIME]
      ,DATEADD(minute, @m, [BATCHHISTORY].[STARTDATETIME]) as [STARTDATETIME]	  
	  ,DATEADD(minute, @m, [BATCHHISTORY].[ENDDATETIME]) as [ENDDATETIME]
	  ,CASE
			WHEN [BATCHHISTORY].STARTDATETIME > '1900-01-01'
			 AND [BATCHHISTORY].ENDDATETIME   > '1900-01-01'
			THEN DATEDIFF_BIG(ss, [BATCHHISTORY].STARTDATETIME, [BATCHHISTORY].enddatetime)
			ELSE NULL
	   END as [DurationSec]
	  ,[BATCHHISTORY].[COMPANY]
      ,[ALERTSPROCESSED]
      ,[BATCHCREATEDBY]
      ,[CANCELEDBY]
	  ,DATEDIFF(mi, [BATCHJOBHISTORY].ORIGSTARTDATETIME, [BATCHJOBHISTORY].STARTDATETIME) as [StartDelayMin]
  FROM [dbo].[BATCHJOBHISTORY], [dbo].[BATCHHISTORY]
where 
[BATCHHISTORY].BATCHJOBHISTORYID = [BATCHJOBHISTORY].RECID and
[BATCHJOBHISTORY].[STARTDATETIME] > '1900-01-01' and
-- filter on [DurationSec] > 2 (alias can't be used in WHERE, so repeat the guarded expression)
[BATCHHISTORY].STARTDATETIME > '1900-01-01' and
[BATCHHISTORY].ENDDATETIME   > '1900-01-01' and
DATEDIFF_BIG(ss, [BATCHHISTORY].STARTDATETIME, [BATCHHISTORY].ENDDATETIME) > 2 and
-- DATEDIFF(mi, [BATCHJOBHISTORY].ORIGSTARTDATETIME, [BATCHJOBHISTORY].STARTDATETIME) > 2 and 
DATEADD(minute, @m, [BATCHJOBHISTORY].[STARTDATETIME]) > CONVERT(datetime, '2026-07-05', 120)
--order by STARTDATETIME desc
--order by CAPTION desc
